// Fiches d'exemple affichées quand aucune base n'est connectée (mode démo).
const noExtras = {
  capacityStanding: null,
  beds: null,
  pricePerNightPerGuest: null,
  catererType: "UNKNOWN",
  catererPricePerGuest: null,
  minSpend: null,
  priceVenue: null,
  exclusivity: null,
  comments: [],
  emails: [],
};

export const DEMO_VENUES = [
  {
    id: "demo-1",
    name: "Château de Vaugrenant",
    category: "LIEU",
    website: "https://example.com",
    country: "FR",
    region: "Bourgogne",
    status: "COMPLETE",
    isFavorite: true,
    price: 9000,
    contactName: "Mme Laurent",
    contactEmail: "contact@example.com",
    contactPhone: "+33 3 80 00 00 00",
    photoUrl:
      "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&q=80",
    capacitySeated: 120,
    capacityStanding: 200,
    beds: 40,
    priceVenue: 9000,
    pricePerNightPerGuest: 60,
    catererType: "IMPOSED",
    catererPricePerGuest: 130,
    minSpend: null,
    availabilityNotes: "Quelques samedis libres en juin et septembre 2027.",
    exclusivity: true,
    notes: "Privatisation totale, parc de 8 hectares, hébergement sur place.",
    comments: [
      {
        id: "c1",
        body: "Coup de cœur ! Le parc est magnifique.",
        author: "Nicole",
        createdAt: "2026-06-10T10:00:00.000Z",
      },
    ],
    emails: [
      {
        id: "e1",
        direction: "OUTBOUND",
        subject: "Demande d'informations - mariage",
        body: "Bonjour, votre lieu nous intéresse beaucoup pour notre mariage (~150 invités). Pourriez-vous préciser vos disponibilités 2027, le tarif et le traiteur ? Merci !",
        fromAddr: "alicerota91@gmail.com",
        toAddr: "contact@example.com",
        createdAt: "2026-06-11T09:00:00.000Z",
      },
      {
        id: "e2",
        direction: "INBOUND",
        subject: "Re: Demande d'informations - mariage",
        body: "Bonjour, avec plaisir ! Samedis libres en juin et septembre 2027. Privatisation week-end à 9 000 €, traiteur imposé à 130 €/personne. Bien à vous.",
        fromAddr: "contact@example.com",
        toAddr: "alicerota91@gmail.com",
        createdAt: "2026-06-12T14:30:00.000Z",
      },
    ],
  },
  {
    id: "demo-2",
    name: "Mas des Oliviers",
    category: "LIEU",
    website: "https://example.com",
    country: "FR",
    region: "Provence",
    status: "REPLIED",
    isFavorite: false,
    price: 6500,
    contactName: "M. Roux",
    contactEmail: "contact@example.com",
    contactPhone: null,
    photoUrl:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
    capacitySeated: 90,
    capacityStanding: 140,
    beds: 24,
    priceVenue: 6500,
    pricePerNightPerGuest: 45,
    catererType: "FREE",
    catererPricePerGuest: 95,
    minSpend: null,
    availabilityNotes: "Disponible la plupart des week-ends hors juillet/août.",
    exclusivity: true,
    notes: "Traiteur libre, vue sur les vignes, piscine.",
    comments: [],
    emails: [],
  },
  {
    id: "demo-3",
    name: "Studio Lumière",
    category: "PHOTOGRAPHE",
    website: "https://example.com",
    country: "FR",
    region: "Lyon",
    status: "ENRICHED",
    isFavorite: true,
    price: 2400,
    contactName: "Camille",
    contactEmail: "camille@example.com",
    contactPhone: "+33 6 12 34 56 78",
    photoUrl:
      "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80",
    capacitySeated: null,
    availabilityNotes: "Disponible week-ends de mai à octobre 2027.",
    notes: "Forfait journée complète + album, style reportage naturel.",
    ...noExtras,
  },
  {
    id: "demo-4",
    name: "Atelier Pivoine",
    category: "FLEURISTE",
    website: "https://example.com",
    country: "FR",
    region: "Provence",
    status: "PENDING",
    isFavorite: false,
    price: 1800,
    contactName: null,
    contactEmail: "hello@example.com",
    contactPhone: null,
    photoUrl:
      "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?w=800&q=80",
    capacitySeated: null,
    availabilityNotes: null,
    notes: "Compositions champêtres, fleurs de saison.",
    ...noExtras,
  },
];
