// Fiches d'exemple affichées quand aucune base n'est connectée (mode démo).
// Permet de visualiser le rendu sans aucune configuration.
export const DEMO_VENUES = [
  {
    id: "demo-1",
    name: "Château de Vaugrenant",
    website: "https://example.com",
    country: "FR",
    region: "Bourgogne",
    status: "COMPLETE",
    contactName: "Mme Laurent",
    contactEmail: "contact@example.com",
    contactPhone: "+33 3 80 00 00 00",
    photoUrl:
      "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&q=80",
    capacitySeated: 120,
    capacityStanding: 200,
    beds: 40,
    priceVenue: 9000,
    pricePerNightPerGuest: 60,
    catererType: "IMPOSED",
    catererPricePerGuest: 130,
    minSpend: null,
    availabilityNotes: "Quelques samedis libres en juin et septembre 2027.",
    exclusivity: true,
    notes: "Privatisation totale, parc de 8 hectares, hébergement sur place.",
  },
  {
    id: "demo-2",
    name: "Mas des Oliviers",
    website: "https://example.com",
    country: "FR",
    region: "Provence",
    status: "REPLIED",
    contactName: "M. Roux",
    contactEmail: "contact@example.com",
    contactPhone: null,
    photoUrl:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
    capacitySeated: 90,
    capacityStanding: 140,
    beds: 24,
    priceVenue: 6500,
    pricePerNightPerGuest: 45,
    catererType: "FREE",
    catererPricePerGuest: 95,
    minSpend: null,
    availabilityNotes: "Disponible la plupart des week-ends hors juillet/août.",
    exclusivity: true,
    notes: "Traiteur libre, vue sur les vignes, piscine.",
  },
  {
    id: "demo-3",
    name: "Villa Toscana",
    website: "https://example.com",
    country: "IT",
    region: "Toscane",
    status: "ENRICHED",
    contactName: null,
    contactEmail: "contact@example.com",
    contactPhone: "+39 055 000 000",
    photoUrl:
      "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
    capacitySeated: 110,
    capacityStanding: 180,
    beds: 30,
    priceVenue: 12000,
    pricePerNightPerGuest: 80,
    catererType: "INCLUDED",
    catererPricePerGuest: 150,
    minSpend: 25000,
    availabilityNotes: null,
    exclusivity: true,
    notes: "Domaine viticole, traiteur maison, coordinateur sur place.",
  },
];
