// Fiches d'exemple affichées quand aucune base n'est connectée (mode démo).
// Permet de visualiser le rendu sans aucune configuration.
export const DEMO_VENUES = [
  {
    id: "demo-1",
    name: "Château de Vaugrenant",
    website: "https://example.com",
    country: "FR",
    region: "Bourgogne",
    status: "COMPLETE",
    isFavorite: true,
    contactName: "Mme Laurent",
    contactEmail: "contact@example.com",
    contactPhone: "+33 3 80 00 00 00",
    photoUrl:
      "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&q=80",
    capacitySeated: 120,
    capacityStanding: 200,
    beds: 40,
    priceVenue: 9000,
    pricePerNightPerGuest: 60,
    catererType: "IMPOSED",
    catererPricePerGuest: 130,
    minSpend: null,
    availabilityNotes: "Quelques samedis libres en juin et septembre 2027.",
    exclusivity: true,
    notes: "Privatisation totale, parc de 8 hectares, hébergement sur place.",
    comments: [
      {
        id: "c1",
        body: "Coup de cœur ! Le parc est magnifique, à recontacter pour la dispo de septembre.",
        author: "Nicole",
        createdAt: "2026-06-10T10:00:00.000Z",
      },
    ],
    emails: [
      {
        id: "e1",
        direction: "OUTBOUND",
        subject: "Demande d'informations - mariage",
        body: "Bonjour, votre domaine nous intéresse beaucoup pour notre mariage (environ 150 invités). Pourriez-vous nous préciser vos disponibilités en 2027, le tarif de location et le traiteur ? Merci !",
        fromAddr: "alicerota91@gmail.com",
        toAddr: "contact@example.com",
        createdAt: "2026-06-11T09:00:00.000Z",
      },
      {
        id: "e2",
        direction: "INBOUND",
        subject: "Re: Demande d'informations - mariage",
        body: "Bonjour, avec plaisir ! Nous avons quelques samedis libres en juin et septembre 2027. La privatisation du week-end est à 9 000 €, le traiteur est imposé à 130 € par personne. N'hésitez pas à venir visiter. Bien à vous.",
        fromAddr: "contact@example.com",
        toAddr: "alicerota91@gmail.com",
        createdAt: "2026-06-12T14:30:00.000Z",
      },
    ],
  },
  {
    id: "demo-2",
    name: "Mas des Oliviers",
    website: "https://example.com",
    country: "FR",
    region: "Provence",
    status: "REPLIED",
    isFavorite: false,
    contactName: "M. Roux",
    contactEmail: "contact@example.com",
    contactPhone: null,
    photoUrl:
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
    capacitySeated: 90,
    capacityStanding: 140,
    beds: 24,
    priceVenue: 6500,
    pricePerNightPerGuest: 45,
    catererType: "FREE",
    catererPricePerGuest: 95,
    minSpend: null,
    availabilityNotes: "Disponible la plupart des week-ends hors juillet/août.",
    exclusivity: true,
    notes: "Traiteur libre, vue sur les vignes, piscine.",
    comments: [],
    emails: [],
  },
  {
    id: "demo-3",
    name: "Villa Toscana",
    website: "https://example.com",
    country: "IT",
    region: "Toscane",
    status: "ENRICHED",
    isFavorite: false,
    contactName: null,
    contactEmail: "contact@example.com",
    contactPhone: "+39 055 000 000",
    photoUrl:
      "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&q=80",
    capacitySeated: 110,
    capacityStanding: 180,
    beds: 30,
    priceVenue: 12000,
    pricePerNightPerGuest: 80,
    catererType: "INCLUDED",
    catererPricePerGuest: 150,
    minSpend: 25000,
    availabilityNotes: null,
    exclusivity: true,
    notes: "Domaine viticole, traiteur maison, coordinateur sur place.",
    comments: [],
    emails: [],
  },
];
